layout_spectrum: 0.5404721
typography_spectrum: 0.6551433
color:
  saturation: 0.6922429
  lightness: 0.6079258
  brandStrength: 0.9055649
  rhythmicContrast: 0.6112985
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Artemisltd.net
